"""Make start_time nullable

Revision ID: a7fb19de1e51
Revises: 92b7be65d8ad
Create Date: 2025-03-02 07:54:35.452878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fb19de1e51'
down_revision = '92b7be65d8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
